### ISSUE TITLE
无法Ping SSPanel

### ISSUE THREAD

**Issue by Bill0412** [fanvinga/dockerfiles#12]
Environment 环境
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。
与Docker版本后端fanvinga/docker-ssrmu搭配使用

Bug
The bug information. 请描述你遇到的 Bug。
前端用https://blog.anank.ke/w/SSPanel_with_LNMP 教程，后端用fanvinga/docker-ssrmu，在docker运行的log里会出现，应该是最近的一次对方SSPanel route.php更改后出现的问题。
是有一个问号的出入，应该是那边的接口改了。

2019-12-30 04:34:33 ERROR web_transfer.py:672 Traceback (most recent call last):
File "/root/shadowsocks/webapi_utils.py", line 23, in getApi
timeout=10)
File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
return self.request('GET', url, **kwargs)
File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 519, in request
prep = self.prepare_request(req)
File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 462, in prepare_request
hooks=merge_hooks(request.hooks, self.hooks),
File "/usr/lib/python3.7/site-packages/requests/models.py", line 313, in prepare
self.prepare_url(url, params)
File "/usr/lib/python3.7/site-packages/requests/models.py", line 387, in prepare_url
raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '<my_server_ip>/mod_mu/func/ping': No schema supplied. Perhaps you meant http://<my_server_ip>/mod_mu/func/ping?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/root/shadowsocks/web_transfer.py", line 660, in thread_db
ping = webapi.getApi('func/ping')
File "/root/shadowsocks/webapi_utils.py", line 39, in getApi
raise Exception('network issue or server error!')
Exception: network issue or server error!

Reproduce
Steps to reproduce the bug. 请逐步描述如何复现 Bug。
如上述，用HyperApp的Docker后端

Expected behavior
What you expected to happen. 请描述你预期的行为。
最好能有分支支持

Logs
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

Addition
Additional context here. 如有可能，请提供更多相关资料。
关于ping的接口：

1. https://blog.fly2x.cn/archives/36/

**Comment by Bill0412** [comment]
发现URL用https加域名形式就成功了。

**Comment by Bill0412** [comment]
如上
